base:
  project: winequality-project
  random_state: 42
  target_col: quality

data_source:
  s3_source: data_given/winequality-red.csv

load_data:
  raw_dataset_csv: data/raw/winequality-red.csv

split_data:
  train_path: data/processed/train_winequality-red.csv
  test_path: data/processed/test_winequality-red.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
#      alpha: 0.5
#      l1_ratio: 0.5
      alpha: 0.95
      l1_ratio: 0.4

model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet regression
  run_name: mlops
  registered_model_name: ElasticNetWineModel
  remote_server_uri: sqlite:///mlruns.db
  #http://0.0.0.0:1234